// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKag6h-pSiUKdQy0UEqY9eJ-pegSP4asU',
    appId: '1:190984185869:web:d333cea80087f6af63cd44',
    messagingSenderId: '190984185869',
    projectId: 'deck-note',
    authDomain: 'deck-note.firebaseapp.com',
    storageBucket: 'deck-note.firebasestorage.app',
    measurementId: 'G-Q1SX6MV4ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWIFNAWr1mTijsWZT7fPSsAMRkNjhzndQ',
    appId: '1:190984185869:android:a20955d6339801a263cd44',
    messagingSenderId: '190984185869',
    projectId: 'deck-note',
    storageBucket: 'deck-note.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJwsSCj1iL72aswEGOSut_eTSbX7EPpI',
    appId: '1:190984185869:ios:b639bc84accb343363cd44',
    messagingSenderId: '190984185869',
    projectId: 'deck-note',
    storageBucket: 'deck-note.firebasestorage.app',
    iosClientId: '190984185869-tukk8mo7mrdstrj33fvgnnk6eutqjgb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.deckNote',
  );
}
